[app]
gitlab.project.base.url = "https://gitlab.com/yourcompany/awesomeproject"
gitlab.repo = "${GIT_REPO}" # tip: to take advantage of it, it's recommended to have your project folder name equals GitLab repo name
gitlab.branch = "master"

[vars.build-dev]
ENV = "dev"
GIT_BRANCH = "feat/awesome-feature-to-be-build"

[vars.deploy-dev]
ENV = "dev"
GIT_BRANCH = "feat/awesome-feature-to-be-deployed"

[vars.build-deploy-stg]
ENV = "staging"
GIT_BRANCH = "${GIT_HEAD}" # current git HEAD branch
